services:
#    codeko_login_principal.example:
#        class: Codeko\LoginPrincipalBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]
    codeko_user.my_provider:
        class: Codeko\LoginPrincipalBundle\Security\Provider\MyProvider
        public: false
        arguments: ["@fos_user.user_manager"]
        
    codeko_user.registration.form.type:
        class: Codeko\LoginPrincipalBundle\Form\RegistrationFormType
        arguments: [%fos_user.model.user.class%]
        tags:
            - { name: form.type, alias: user_registration }