permisoCategoriaUser:
    path:     /
    defaults: { _controller: "ApplicationSonataUserBundle:PermisoCategoriaUser:index" }

permisoCategoriaUser_show:
    path:     /{id}/show
    defaults: { _controller: "ApplicationSonataUserBundle:PermisoCategoriaUser:show" }

permisoCategoriaUser_new:
    path:     /new
    defaults: { _controller: "ApplicationSonataUserBundle:PermisoCategoriaUser:new" }

permisoCategoriaUser_create:
    path:     /create
    defaults: { _controller: "ApplicationSonataUserBundle:PermisoCategoriaUser:create" }
    methods:  POST

permisoCategoriaUser_edit:
    path:     /{id}/edit
    defaults: { _controller: "ApplicationSonataUserBundle:PermisoCategoriaUser:edit" }

permisoCategoriaUser_update:
    path:     /{id}/update
    defaults: { _controller: "ApplicationSonataUserBundle:PermisoCategoriaUser:update" }
    methods:  [POST, PUT]

permisoCategoriaUser_delete:
    path:     /{id}/delete
    defaults: { _controller: "ApplicationSonataUserBundle:PermisoCategoriaUser:delete" }
    methods:  [POST, DELETE]
