## Security Routes
default:
    pattern:   /
    defaults:  { _controller: AcmeUserBundle:Security:login }

login:
    pattern:   /login
    defaults:  { _controller: AcmeUserBundle:Security:login }

login_check:
    pattern:   /login_check

logout:
    pattern: /logout