<?php

namespace Acme\LoginPrincipalBundle\Controller;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class PrincipalController__JMSInjector
{
    public static function inject($container) {
        $instance = new \Acme\LoginPrincipalBundle\Controller\PrincipalController();
        return $instance;
    }
}
