<?php

namespace Sonata\AdminBundle\Controller;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class CRUDController__JMSInjector
{
    public static function inject($container) {
        $instance = new \Sonata\AdminBundle\Controller\CRUDController();
        return $instance;
    }
}
