<?php

namespace Sonata\UserBundle\Controller\Api;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class GroupController__JMSInjector
{
    public static function inject($container) {
        $instance = new \Sonata\UserBundle\Controller\Api\GroupController();
        return $instance;
    }
}
