<?php

namespace Sonata\UserBundle\Controller;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class ProfileFOSUser1Controller__JMSInjector
{
    public static function inject($container) {
        $instance = new \Sonata\UserBundle\Controller\ProfileFOSUser1Controller();
        return $instance;
    }
}
