<?php

namespace Sonata\UserBundle\Controller;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class ResettingFOSUser1Controller__JMSInjector
{
    public static function inject($container) {
        $instance = new \Sonata\UserBundle\Controller\ResettingFOSUser1Controller();
        return $instance;
    }
}
