<?php

namespace Sonata\AdminBundle\Controller;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class CoreController__JMSInjector
{
    public static function inject($container) {
        $instance = new \Sonata\AdminBundle\Controller\CoreController();
        return $instance;
    }
}
